# Generated by Django 2.1.15 on 2020-12-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
